---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: queries_match
  regexps:
  - "^celular_de_eli.bateria\\s*$"
  - "^celular_de_eli.saldo\\s*$"
name: Cuestión de estado
