---
locale: es
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: PENDIENTE
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: PENDIENTE 2
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: PENDIENTE 3
  checked: false
name: Ejercicio en construcción
