---
locale: es
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`nano` entiende el mensaje `galopar`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`pepita` entiende el mensaje `galopar`"
  checked: false
name: Jumanji
