---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "`nano` entiende el mensaje `galopar`"
  checked: true
- value: "`pepita` entiende el mensaje `galopar`"
  checked: false
- value: '`"Cuarto De Milla"` es la `ciudad` de `nano`'
  checked: false
- value: "`theo` y `nano` hacen lo mismo cuando reciben el mensaje `comer`"
  checked: false
- value: "`theo` y `kali` hacen lo mismo cuando reciben el mensaje `comer`"
  checked: true
- value: "`kali` tiene más años que `theo`"
  checked: true
- value: Si hacemos `pepita.volar_hacia("Quilmes")` su ciudad será `"Quilmes"` y su
    energía `50`
  checked: false
- value: Si hacemos `nano.comer(100)` su energía será `700`
  checked: true
name: Jumanji
